### ISSUE TITLE
entrophy wins: Goblin Refuge - remain online until at least April 01, 2021

### ISSUE THREAD

**Issue by pflegende** [johnjago/awesome-ad-free#13]
Goblin Refuge - Video and image sharing service powered by MediaGoblin.

https://goblinrefuge.com/mediagoblin/

`Shutdown notice: Goblin Refuge is shutting down. New user registration, file uploads, and comments have been disabled. You can still log in to edit or delete existing media. The site will remain online until at least April 01, 2021.`

**Comment by johnjago** [comment]
@pflegende feel free to move it into the unmaintained section that @Mennaruuk created, possibly with a link to the Wayback Machine.

**Comment by Mennaruuk** [comment]
Created a PR!

Sorry, I'm really bad at PRs, but the latest "Update README.md" commit should suffice.

**Comment by johnjago** [comment]
@Mennaruuk It looks like the latest commit is correct, but the end result of the PR is that the whole file is deleted :upside_down_face: 

Could you try these steps one more time to create a new PR with only one commit?

Click the pencil icon on this file: https://github.com/johnjago/awesome-ad-free/blob/master/README.md

![2021-03-05-165334_393x278_scrot](https://user-images.githubusercontent.com/19847480/110183148-db8db200-7dd3-11eb-9218-23af4bc94f4a.png)

Make the change and write a commit message, then click Propose changes.

I think it may be a little different for you since you already forked the repo, but the end result should show your desired changes in the "Files changed" tab like this: https://github.com/johnjago/awesome-ad-free/pull/14/files (except here the file is deleted)

If you need any help let me know and I can get that commit into a different branch! :slightly_smiling_face:

**Comment by Mennaruuk** [comment]
Should be good to go! Thank you so much for your help :)

**Comment by johnjago** [comment]
Awesome, thanks!
